#Passo a Passo Instalação do Docker e UCP

##Configuração da máquina Master do DNS

    ###Configurar o hostname
    hostnamectl status
    hostnamectl set-hostname meuservidor.meudominio.br


    ###Configurar o sudoers
    user_name ALL=(ALL)  ALL

    --Configurar o hosts
    /etc/hosts
    127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    192.168.207.101 manager.dominio.com.br manager
    192.168.207.104 worker01
    192.168.207.105 worker02
    122.168.207.106 DTR

##Configurar o resolv.conf (gateway)
   /etc/resolv.conf
  --# Generated by NetworkManager
    search localdomain
    nameserver 192.168.207.2


##Configuração do DNS (Zona Master e Reversa)

    cat /etc/resolv.conf
    --# Generated by NetworkManager
    search localdomain
    nameserver 192.168.207.2
    [root@manager kleber]# cat /etc/named.conf
    --# Nome da zona master
    zone "dominio.com.br" IN {
     type master;
     check-names ignore;
     file "/var/named/dominio.com.br";
    };

    # Nome da zona Reversa
    zone "207.168.192.in-addr.arpa" IN {
     type master;
     check-names ignore;
     file "/var/named/192.168.207.101";
    };

##Criação do arquivo Dominio
    [root@manager kleber]# cat /var/named/dominio.com.br
    ;
    $TTL    604800
    @   IN    SOA   manager.dominio.com.br. root.dominio.com.br. (
    19             ; Serial
    604800         ; Refresh
    86400          ; Retry
    2419200        ; Expire
    604800 )       ; Negative Cache TTL
    ;

    @       IN  NS          manager.dominio.com.br.
    @       IN  A           192.168.207.101
    manager IN  A           192.168.207.101

##Criação do Arquivo Reverso
    [root@manager kleber]# cat /var/named/192.168.207.101
    $TTL    604800
    @    IN    SOA   pc.dominio.com.br. root.dominio.com.br. (
    1                   ; Serial
    604800          ; Refresh
    86400            ; Retry
    2419200         ; Expire
    604800 )        ; Negative Cache TTL

    @    IN    NS    dominio.com.br.
    254     IN    PTR     dominio.com.br.


##Habilitar arquivos na máquina Master do DNS
  named-checkconf /etc/named.conf    
  named-checkzone manager.dominio.com.br /var/named/dominio.com.br         
  named-checkzone manager.dominio.com.br /var/named/192.168.207.101
  systemctl start named.service
  chkconfig named on  
  service named on 
  service named start      


-----
